# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c5fe93e3a1b22eb480a9eb3b854bc4d"
name = "aether-intelligence"
handle = "aether-intelligence-1"
application_url = "https://localhost:57839"
auth_callback_path = "/auth/callback"
auth_path = "/auth/shopify/callback"
api_callback_path = "/api/auth/callback"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,read_inventory,read_price_rules,write_price_rules,read_customers,read_analytics"

[auth]
redirect_urls = [
  "https://localhost:57839/auth/callback",
  "https://localhost:57839/auth/shopify/callback",
  "https://localhost:57839/api/auth/callback"
]

[pos]
embedded = true

[[proxies.proxy]]
path = "/api/*"
target = "http://localhost:57839/api"
